config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :users

   root 'static#home'
   get 'about' => 'static#about'
   get 'new_user' => 'users#new'
   get 'login' => 'user_sessions#new'
   post 'login' => 'user_sessions#create'
   get 'logout' => 'user_sessions#destroy'
   get 'cards' => 'cards#index'
   get 'new_card' => 'cards#new'

end

app/models/card.rb
class Card < ActiveRecord::Base
    belongs_to :user 
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include UserSessionsHelper
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  
  rescue_from ActiveRecord::RecordNotFound, with: :no_cards_found
  def index
    if signed_in?
      @cards = Card.where(:user_id => @current_user.id)
    else
      flash[:danger] = "Sorry, you need to sign in or create an account before you can review your cards."
      redirect_to :back
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    if !signed_in? || Card.count < 1
      flash[:danger] = "Sorry, you need to sign in or create an account before you can review your cards."
      redirect_to root_path
    end
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to cards_url, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to cards_url, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:question, :answer, :score, :user_id)
    end
    
    def no_cards_found
        if signed_in?
            redirect_to cards_path
        else
            flash[:danger] = "Sorry, you need to sign in or create an account before you can review your cards."
            redirect_to :back
        end
    end
    
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    @card = Card.new
  end

  def about
  end
  
      # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:question, :answer, :score, :user_id)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def destroy 
      sign_out
      redirect_to root_url
  end
  def create 
    user = User.find_by(name: params[:user_session][:name].downcase)
    if user
        # log in and go to learning page
        log_in user
        render 'static/home'
    else
      flash[:danger] = "Sorry, we do not have a user with that name and e-mail."
      redirect_to :back
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @root_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
    def log_in(user)
        session[:user_id] = user.id 
    end
    def current_user 
        @current_user ||= User.find_by(id: session[:user_id]) 
    end
    def sign_out
        session.delete(:user_id) 
        @current_user = nil
    end
    def signed_in?
        !current_user.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_area :answer %>
  </div>
  <%= f.hidden_field :score, :value => 1 %>
  <% if signed_in? %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <div class="actions">
        <%= f.submit %>
    </div>
  <% else %>
    <!-- don't let the user submit -->
    <p>Sorry. You must be signed in to create new cards.</p>
  <% end %>
  <!--#<div class="field">
  #  <%= f.label :score %><br>
  #  <%= f.number_field :score %>
  #</div>
  #<div class="field">
  #  <%= f.label :user_id %><br>
  #  <%= f.number_field :user_id %>
  #</div>-->
  
<% end %>

app/views/cards/edit.html.erb
<html>
  <head>
    <title>
      Hello, World
    </title>
    <link href="./css/bootstrap/bootstrap.css" rel="stylesheet">
    <link href="./css/bootstrap/navbar.css" rel="stylesheet">
    
    <script type="text/javascript"
            src="http://coffeescript.org/extras/coffee-script.js">
    </script>
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
  </head>

  <body>
    <script>set_up_scalar_form()</script>
    <script>set_up_dot_product_form()</script>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <div class="container">
        <div class="navbar navbar-default">
            <div class="navbar-header">
   
                <a class="navbar-brand" href=<%=root_path%>>Enki</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   <li><a href=<%=about_path%>>about</a></li>
                </ul>
                <ul class="nav navbar-nav">
                   <li><a href=<%=cards_path%>>review my cards</a></li>
                </ul>
                <% if signed_in? %>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=<%=logout_path%>>sign out</a></li>
                </ul>
                <% else %>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=<%=login_path%>>sign in</a></li>
                </ul>
                <% end %>
            </div>
            
        </div>
<h1>Editing Card</h1>

<%= render 'form' %>

<%= link_to 'view this card', @card, :class=>"btn btn-primary" %> 

</body>
</html>

app/views/cards/index.html.erb
<html>
  <head>
    <title>
      Hello, World
    </title>
    <link href="./css/bootstrap/bootstrap.css" rel="stylesheet">
    <link href="./css/bootstrap/navbar.css" rel="stylesheet">
    
    <script type="text/javascript"
            src="http://coffeescript.org/extras/coffee-script.js">
    </script>
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
  </head>

  <body>
    <script>set_up_scalar_form()</script>
    <script>set_up_dot_product_form()</script>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <div class="container">
        <div class="navbar navbar-default">
            <div class="navbar-header">
   
                <a class="navbar-brand" href=<%=root_path%>>Enki</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   <li><a href=<%=about_path%>>about</a></li>
                </ul>
                <ul class="nav navbar-nav">
                   <li><a href=<%=cards_path%>>review my cards</a></li>
                </ul>
                <% if signed_in? %>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=<%=logout_path%>>sign out</a></li>
                </ul>
                <% else %>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=<%=login_path%>>sign in</a></li>
                </ul>
                <% end %>
            </div>
            
        </div>

    <h1>My Cards</h1>
    <div class="row">
        <div class="col-xs-3">
            <h2>Question</h2>
        </div>
        <div class = "col-xs-3">
            <h2>Answer</h2>
        </div>
        <div class = "col-xs-3">
            <h2>Proficiency</h2>
        </div>
    </div>
    <% @cards.each do |card| %>
    <div class = "row">
        <div class="col-xs-3">
            <p><%= card.question %></p>
        </div>
        <div class = "col-xs-3">
            <p><%= card.answer %></p>
        </div>
        <div class = "col-xs-3">
            <p><%= card.score %>/10</p>
        </div>
        <div class = "col-xs-1">
            <%= link_to 'Review', card, :class=>"btn btn-primary" %>
        </div>
        <div class = "col-xs-1">
            <%= link_to 'Edit', edit_card_path(card), :class=>"btn btn-warning" %>
        </div>
        <div class = "col-xs-1">
            <%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger"%>
        </div>
    </div>
    <% end %>

<br>

<%= link_to 'make new card', new_card_path, :class=>"btn btn-primary" %>

</body>
</html>

app/views/cards/new.html.erb
<html>
  <head>
    <title>
      Hello, World
    </title>
    <link href="./css/bootstrap/bootstrap.css" rel="stylesheet">
    <link href="./css/bootstrap/navbar.css" rel="stylesheet">
    
    <script type="text/javascript"
            src="http://coffeescript.org/extras/coffee-script.js">
    </script>
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
  </head>

  <body>
    <script>set_up_scalar_form()</script>
    <script>set_up_dot_product_form()</script>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <div class="container">
        <div class="navbar navbar-default">
            <div class="navbar-header">
   
                <a class="navbar-brand" href=<%=root_path%>>Enki</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   <li><a href=<%=about_path%>>about</a></li>
                </ul>
                <ul class="nav navbar-nav">
                   <li><a href=<%=cards_path%>>review my cards</a></li>
                </ul>
                <% if signed_in? %>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=<%=logout_path%>>sign out</a></li>
                </ul>
                <% else %>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=<%=login_path%>>sign in</a></li>
                </ul>
                <% end %>
            </div>
            
        </div>
<h1>New Card</h1>

<%= render 'form' %>

</body>
</html>

app/views/cards/show.html.erb
<html>
  <head>
    <title>
      Hello, World
    </title>
    <link href="./css/bootstrap/bootstrap.css" rel="stylesheet">
    <link href="./css/bootstrap/navbar.css" rel="stylesheet">
    
    <script type="text/javascript"
            src="http://coffeescript.org/extras/coffee-script.js">
    </script>
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
  </head>

  <body>
    <script>set_up_scalar_form()</script>
    <script>set_up_dot_product_form()</script>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <div class="container">
        <div class="navbar navbar-default">
            <div class="navbar-header">
   
                <a class="navbar-brand" href=<%=root_path%>>Enki</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   <li><a href=<%=about_path%>>about</a></li>
                </ul>
                <ul class="nav navbar-nav">
                   <li><a href=<%=cards_path%>>review my cards</a></li>
                </ul>
                <% if signed_in? %>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=<%=logout_path%>>sign out</a></li>
                </ul>
                <% else %>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=<%=login_path%>>sign in</a></li>
                </ul>
                <% end %>
            </div>
            
        </div>
<p>
  <strong>Question:</strong>
  <%= @card.question %>
</p>

<button type="button" class="btn btn-primary" onclick="show_solution()">Show the solution</button>
<p id = "answer", style="visibility:hidden">
<br>
   <%= @card.answer %>
</p>
    <p>
        <br>
        How did you do?
    </p>
    <!--<button type="button" class="btn btn-success" >Got it!</button>-->
    <div class = "row">
        <div class = "col-xs-1">
            <%= form_for(@card) do |f| %>
                <% if @card.score < 5 %>
                    <%= f.hidden_field :score, :value => @card.score + 1%>
                    <%= f.submit :'got it!', :class=>"btn btn-success"%>
                <% else %>
                 <!-- this shouldn't happen when I've finished, but just in case, let's put an empty button here -->
                  <%= link_to 'Got it!', cards_path, :class=>"btn btn-success" %>
                <% end %>
            <% end %>
        </div>
        <div class = "col-xs-1">
            <%= form_for(@card) do |f| %>
                <% if @card.score > 1 %>
                    <%= f.hidden_field :score, :value => @card.score - 1%>
                    <%= f.submit :'not yet', :class=>"btn btn-danger"%>
                <% else %>
                 <!-- this shouldn't happen when I've finished, but just in case, let's put an empty button here -->
                    <%= link_to 'Not yet', cards_path, :class=>"btn btn-danger" %>
                <% end %>
            <% end %>
        </div>
    </div>



<p><br><br><%= link_to 'edit this card', edit_card_path(@card) %> </p></div>

    <script type="text/coffeescript">
        @show_solution = () ->
            document.getElementById("answer").style.visibility = "visible"
            reload_typeset()
            

    </script>

</body>
</html>
            
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enki</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_sessions/new.html.erb
<html>
  <head>
    <title>
     Enki
    </title>
    <link href="./css/bootstrap/bootstrap.css" rel="stylesheet">
    <link href="./css/bootstrap/navbar.css" rel="stylesheet">
    
    <script type="text/javascript"
            src="http://coffeescript.org/extras/coffee-script.js">
    </script>
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
  </head>

  <body>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <div class="container">
        <div class="navbar navbar-default">
            <div class="navbar-header">
   
                <a class="navbar-brand" href="/">Enki</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   <li><a href="about">about</a></li>
                </ul>
                <ul class="nav navbar-nav">
                   <li><a href="cards">review my cards</a></li>
                </ul>
                <% if signed_in? %>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="logout">sign out</a></li>
                </ul>
                <% else %>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="login">sign in</a></li>
                </ul>
                <% end %>
                
            </div>
            
        </div>
<% provide(:title, "Sign in") %>
<h1> Log in </h1>
<div class="row">
    <div class="col-xs-6">
        <%= form_for(:user_session, url:login_path) do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form_control' %>
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form_control' %>
            <%= f.submit "Sign in", class: "btn btn-default" %>
        <% end %>
        <p>New to Enki?<%= link_to "Sign up!", new_user_path %></p>
    </div>
</div>
</body>
</html>
            
    

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>